language: java
install: true

jdk:
- openjdk11

before_install:
# What Gradle version is Travis trying to use
#- gradle -v
# Download desired version of Gradle
- wget https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
- unzip -qq gradle-4.10.2-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.10.2
- export PATH=$GRADLE_HOME/bin:$PATH
# just to test gradle version, against our provided one
- gradle -v

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.5.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://feb7e831900d14398a93305512ce3a4c98b4d254@github.com/TheLazyHatGuy/OOP-CA4 --tags

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
- gradle assemble
- gradle test
- gradle serverJar
- gradle clientJar

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 'feb7e831900d14398a93305512ce3a4c98b4d254'
  file:
    - "./build/libs/Server-0.5.jar"
    - "./build/libs/Client-0.5.jar"
  on:
    tags: false
    branch: master

branches:
  except:
    - /^*-v[0-9]/
